<?php
 
require 'vendor/autoload.php';
$app = new \Slim\Slim();

//setup jwt auth
/*
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub"
]));
*/
#########################
######## Routes #########
#########################


$app->get('/', function() use($app) {
    $app->response->setStatus(200);
    echo "Reach API v1.0";
}); 

$app->post('/login', function() use($app) {
    $app->response->setStatus(200);
    doLogin();

});

$app->options('/login', function() use($app) {
    $app->response->setStatus(200);
});

//user
$app->get('/user', function() use($app) {
    $app->response->setStatus(200);
    getAllUsers();
});

$app->get('/user/:uid', function($uid) use($app) {
    $app->response->setStatus(200);
    getUser($uid);
});

$app->post('/user', function() use($app) {
    $app->response->setStatus(200);
    updateUser();
});

$app->get('/company', function() use($app) {
    $app->response->setStatus(200);
    getAllCompanies();
});

$app->get('/company/:cid', function($cid) use($app) {
    $app->response->setStatus(200);
    getCompany($cid);
});

$app->get('/company/:cid/employees', function($cid) use($app) {
    $app->response->setStatus(200);
    getAllEmployees($cid);
});

$app->get('/company/:cid/customers', function($cid) use($app) {
    $app->response->setStatus(200);
    getAllCustomers($cid);
});


//message
/*
$app->get('/message/:uid/:timestamp', function() use($app) {
    $app->response->setStatus(200);
    getMessages($uid,$timestamp);
});
*/

$app->post('/message', function() use($app) {
    $app->response->setStatus(200);
    createMessage();
});

$app->get('/message', function() use($app) {
    $app->response->setStatus(200);
    echo'
       <html><body><form method="post">
       <br>sender:<input name="sender_uid">
       <br>recip: <input name="recipient_uid">
       <br>message:<input name="message_content">
       <br><input type="submit"> 
      </form></body></html>
    ';
});


//bulletin
$app->get('/bulletin/:cid/:timestamp', function() use($app) {
    $app->response->setStatus(200);
    getBulletins($cid,$timestamp);
});

$app->post('/bulletin', function() use($app) {
    $app->response->setStatus(200);
    sendBulletin();
});

############################################
############ Utility functions #############
############################################

function doLogin() {

    $config = array(
        'jwt' => array(
          'key'       => 'supersecretkeyyoushouldnotcommittogithub',     // Key for signing the JWT's, I suggest generate it with base64_encode(openssl_random_pseudo_bytes(64))
          'algorithm' => 'HS512' // Algorithm used to sign the token, see https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3
          ),
        'serverName' => 'http://52.27.2.199/'
    );

    $username = $_POST['email'];
    $password = $_POST['password'];
    
    if ($username && $password) {
        try {
    
            $sql = "SELECT * FROM users WHERE email=:email";
    
            $db = getDBConnection();
            $stmt = $db->prepare($sql);
            $stmt->bindParam("email", $username);
            $stmt->execute();
            $rs = $stmt->fetchAll(PDO::FETCH_OBJ);
            $rs = (array)$rs[0];
            if ($rs) {
                /*
                 * Password was generated by password_hash(), so we need to use
                 * password_verify() to check it.
                 * 
                 * @see http://php.net/manual/en/ref.password.php
                 */
                if (md5($password) === $rs['encrypted_password']) {
                   $random = mt_rand(0, 999999); 
                    $tokenId = base64_encode($random);
                    //$tokenId    = base64_encode(mcrypt_create_iv(32));
                    $issuedAt   = time();
                    $notBefore  = $issuedAt + 10;  //Adding 10 seconds
                    $expire     = $notBefore + 60; // Adding 60 seconds
                    $serverName = $config['serverName'];
                    
                    $perms = getPerms($rs['uid']);

                    /*
                     * Create the token as an array
                     */
                    $data = array(
                        'iat'  => $issuedAt,         // Issued at: time when the token was generated
                        'jti'  => $tokenId,          // Json Token Id: an unique identifier for the token
                        'iss'  => $serverName,       // Issuer
                        'nbf'  => $notBefore,        // Not before
                        'exp'  => $expire,           // Expire
                        'data' => array(                  // Data related to the signer user
                            'userId'   => $rs['uid'], // userid from the users table
                            'userName' => $username, // User name
                            'perms' => $perms
                        )
                    );
                    
                    //header('Content-type: application/json');
                    /*
                     * Extract the key, which is coming from the config file. 
                     * 
                     * Best suggestion is the key to be a binary string and 
                     * store it in encoded in a config file. 
                     *
                     * Can be generated with base64_encode(openssl_random_pseudo_bytes(64));
                     *
                     * keep it secure! You'll need the exact key to verify the 
                     * token later.
                     */
                    $secretKey = base64_decode($config['jwt']['key']);
                    
                    /*
                     * Extract the algorithm from the config file too
                     */
                    $algorithm = $config['jwt']['algorithm'];
                    
                    /*
                     * Encode the array to a JWT string.
                     * Second parameter is the key to encode the token.
                     * 
                     * The output string can be validated at http://jwt.io/
                     */
                    $jwt = \Firebase\JWT\JWT::encode(
                        $data,      //Data to be encoded in the JWT
                        $secretKey, // The signing key
                        $algorithm  // Algorithm used to sign the token, see https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3
                        );
                        
                    $unencodedArray = array('jwt' => $jwt);
                    //$app->response->setStatus(200);
                    echo json_encode($unencodedArray);
                } else {
                    header('HTTP/1.0 401 Unauthorized');
                }
            } else {
                header('HTTP/1.0 404 Not Found');
            }
        } catch (Exception $e) {
            header('HTTP/1.0 500 Internal Server Error');
        }
    } else {
        header('HTTP/1.0 400 Bad Request');
    }

/*

    //we should hash this before ?
    $sql = "SELECT * FROM users WHERE email=:email AND encrypted_password=MD5(:password)";

    $email = $_POST['email'];
    $password = $_POST['password'];

    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("email", $email);
        $stmt->bindParam("password", $password);
        $stmt->execute();
        $user = $stmt->fetchAll(PDO::FETCH_OBJ);
        //$db = null;

        echo json_encode($user[0]);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
*/

}


function getAllUsers() {
    $sql = "SELECT * FROM users";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->execute();
        $users = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo '{"users": ' . json_encode($users) . '}';
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function getUser($uid) {
    $sql = "SELECT * FROM users WHERE uid=:uid";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("uid", $uid);
        $stmt->execute();
        $user = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo json_encode($user[0]);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function createUser() {

    //xxx should check if user already exists

    $sql = "INSERT INTO users
            ('email','encrypted_password','first_name','last_name') 
            VALUES 
            (:email,:encrypted_password,:first_name,:last_name)";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("uid", $uid);
        $stmt->execute();
        $db = null;
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function updateUser() {}

function getAllEmployees($cid) {

    $sql = "SELECT u.uid,u.first_name,u.last_name FROM users u, perms p WHERE p.cid=:cid AND u.uid=p.uid AND p.role='employee'";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("cid", $cid);
        $stmt->execute();
        $user = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo json_encode($user);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function getAllCustomers($cid) {

    $sql = "SELECT u.uid,u.first_name,u.last_name FROM users u, perms p WHERE p.cid=:cid AND u.uid=p.uid AND p.role='customer'";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("cid", $cid);
        $stmt->execute();
        $user = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo json_encode($user);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function createMessage() {

    //insert the message into the database as unsent
    $sql = "INSERT INTO messages 
            (sender_uid,recipient_uid,message_content,timestamp_sent,timestamp_received) 
            VALUES 
            (:sender_uid,:recipient_uid,:message_content,:timestamp_sent,:timestamp_received)";
    //xxx validate data
    $sender_uid = $_POST['sender_uid'];
    $recipient_uid = $_POST['recipient_uid'];
    $message_content = $_POST['message_content'];
    $current_time = time();
    $received_time = 0;

    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("sender_uid", $sender_uid);
        $stmt->bindParam("recipient_uid", $recipient_uid);
        $stmt->bindParam("message_content", $message_content);
        $stmt->bindParam("timestamp_sent", $current_time);
        $stmt->bindParam("timestamp_received", $received_time);
        $stmt->execute();
        $db = null;
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }

    //queue the message for delivery / deliver the message
    $data = array('name' => $sender_uid, 'message' => $message_content);
    $pusher = getPusher();
    $pusher->trigger( 'my_channel'.$recipient_uid, 'my_event', $data );

}

function getMessages($uid,$time=NULL) {

}

function getAllCompanies() {
    $sql = "SELECT * FROM companies";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->execute();
        $companies = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo json_encode($companies);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }
}

function getCompany($cid) {

    $sql = "SELECT * FROM companies WHERE cid=:cid";
    try {
        $db = getDBConnection();
        $stmt = $db->prepare($sql);
        $stmt->bindParam("cid", $cid);
        $stmt->execute();
        $company = $stmt->fetchAll(PDO::FETCH_OBJ);
        $db = null;
        echo json_encode($company[0]);
    } catch(PDOException $e) {
        echo '{"error":{"text":'. $e->getMessage() .'}}';
    }

}


function createBulletin() {}
function getBulletins($uid,$time=NULL) {}

function sendInvite() {}
function processInviteAck() {}

function sendRequest() {}
function processRequestAck() {}


function getPerms($uid) {

            $sql = "SELECT * FROM perms WHERE uid=:uid";
    
            $db = getDBConnection();
            $stmt = $db->prepare($sql);
            $stmt->bindParam("uid", $uid);
            $stmt->execute();
            $rs = $stmt->fetchAll(PDO::FETCH_OBJ);
            $db = null;
            return $rs;
}


function getDBConnection() {
    $dbhost="127.0.0.1";
    $dbuser="reachdb";
    $dbpass="reachdb123";
    $dbname="reach_app";
    $dbh = new PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpass);
    $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    return $dbh;
}

function getPusher() {

    $app_id = '140562';
    $app_key = '95129dfbfbc16ec4a811';
    $app_secret = '1a5dac7bf5d8f1fd9c33';

    $pusher = new Pusher( $app_key, $app_secret, $app_id );

    return $pusher;
}

$app->run();
